input {
  gelf {
    port => 12201
  }
}

filter {
  json {
    source => "message"
    target => "pino"
  }

  date {
    match => ["[pino][time]", "UNIX_MS"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["message", "host", "path", "@version"]
  }

}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "docker-logs-%{+YYYY.MM.dd}"
  }

  stdout { codec => rubydebug }
}
