version: '3.8'

services:
  prometheus:
    container_name: prometheus
    build:
      context: ./prometheus
      dockerfile: Dockerfile
    volumes:
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - monitoring-tier
    restart: always

  grafana:
    container_name: grafana
    build:
      context: ./grafana
      dockerfile: Dockerfile
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_DEFAULT_THEME=light
      - GF_AUTH_ANONYMOUS_ENABLED=false
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
    networks:
      - monitoring-tier
    restart: always

  node-exporter:
    container_name: node-exporter
    image: quay.io/prometheus/node-exporter:v1.8.2
    ports:
      - "9100:9100"
    volumes:
      - /:/host:ro
    command:
      - '--path.rootfs=/host'
    networks:
      - monitoring-tier
    restart: always

  cadvisor:
    container_name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    ports:
      - "8080:8080"
    volumes:
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - monitoring-tier
    restart: always

  nginx-exporter:
    container_name: nginx-exporter
    image: nginx/nginx-prometheus-exporter:1.1.0
    command:
      - '--nginx.scrape-uri=http://nginx:8080/nginx_status'
    ports:
      - '9113:9113'
    networks:
      - monitoring-tier
    restart: always

  alertmanager:
    container_name: alerting
    image: prom/alertmanager:v0.26.0
    ports:
      - '9093:9093'
    volumes:
      - ./alertmanager/config.yml:/etc/alertmanager/alertmanager.yml
    networks:
      - monitoring-tier
    restart: always

volumes:
  prometheus-data:
  grafana-data:

networks:
  monitoring-tier:


